### ISSUE TITLE
Before release checklist

### ISSUE THREAD

**Issue by chrismgonzalez** [chrismgonzalez/chrismgonzalezv3#1]
- [x] Google Analytics ID
- [x] Syntax highlighting
- [x] Mobile first
- [ ] Newsletter sign-up
- [ ] Add a timeline to showcase professional milestones
- [x] About me component for each blog post
- [ ] Cross post to Dev.To
